### ISSUE TITLE
Respawns

### ISSUE THREAD

**Issue by Centralan** [Centralan/Code4-CTF-Event#16]
Need to figure out respawns for players, right now death in the event world will bring you to the creative world

**Comment by Centralan** [comment]
@Kruithne

**Comment by Kruithne** [comment]
Updated the Code4 world to use itself as a respawn world. When players die they will now be teleported to the spawn point for that world, which can be set using '/mv setspawn'.

I've also disabled bed respawning for this world so players who have a bed location in another world shouldn't end up there.
