### ISSUE TITLE
Flag Scoreing Bug

### ISSUE THREAD

**Issue by Centralan** [Centralan/Code4-CTF-Event#8]
function green_flag_score(data, key, location)
    local player = Player:new(data.player);
    if player:hasItemWithName("&cGreen Flag") then
        a_broadcast_npc(Overlord, data.player .. "has captured the Green Flag!", player);
    else
        flag_score_error(player);
    end
end

function blue_flag_score(data, key, location)
    local player = Player:new(data.player);
    if player:hasItemWithName("&cBlue Flag") then
        a_broadcast_npc(Overlord, data.player .. "has captured the Blue Flag!", player);
    else
        flag_score_error(player);
    end
end

This is not working as intended, instead player is getting an error message.

**Comment by Kruithne** [comment]
Didn't we fix this one?

**Comment by Centralan** [comment]
We tryed to fix a bug very close to this with item pickup's, we had an issue with item names (if player:hasItemWithName("&cBlue Flag") then) the same thing is an issue here. The script isnt taking the names and giving the error message when trying to score with the wrong flag.

**Comment by Centralan** [comment]
Removed the color from the name of the flag, now it scores. This bug is closed a new one has opened.
